### ISSUE TITLE
Error injecting: io.github.swagger2markup.Swagger2MarkupMojo

### ISSUE THREAD

**Issue by hpatel2017** [Swagger2Markup/swagger2markup-maven-project-template#6]
Hi,

I tried to build swagger2markup-maven-project-template with url input, but it failed with below error : 

May 24, 2017 4:54:39 PM org.sonatype.guice.bean.reflect.Logs$JULSink warn
WARNING: Error injecting: io.github.swagger2markup.Swagger2MarkupMojo
java.lang.TypeNotPresentException: Type io.github.swagger2markup.Swagger2MarkupMojo not present
        at org.sonatype.guice.bean.reflect.URLClassSpace.loadClass(URLClassSpace.java:109)
        at org.sonatype.guice.bean.reflect.NamedClass.load(NamedClass.java:45)
        at org.sonatype.guice.bean.reflect.AbstractDeferredClass.get(AbstractDeferredClass.java:45)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:84)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:52)
        at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)
        at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager.onProvision(PlexusLifecycleManager.java:138)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:108)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
        at com.google.inject.internal.InjectorImpl$3$1.call(InjectorImpl.java:965)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1011)
        at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:961)
        at com.google.inject.Scopes$1$1.get(Scopes.java:59)
        at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:83)
        at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:49)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:253)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:245)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:455)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:92)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: java.lang.UnsupportedClassVersionError: io/github/swagger2markup/Swagger2MarkupMojo : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:386)
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:244)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:230)
        at org.sonatype.guice.bean.reflect.URLClassSpace.loadClass(URLClassSpace.java:101)
        ... 41 more

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.676s
[INFO] Finished at: Wed May 24 16:54:39 IST 2017
[INFO] Final Memory: 9M/57M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.github.swagger2markup:swagger2markup-maven-plugin:1.3.1:convertSwagger2markup (default-cli) on project swagger2markup-maven-project-template: Execution default-cli of goal io.github.swagger2markup:swagger2markup-maven-plugin:1.3.1:convertSwagger2markup failed: Unable to load the mojo 'convertSwagger2markup' in the plugin 'io.github.swagger2markup:swagger2markup-maven-plugin:1.3.1' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: io/github/swagger2markup/Swagger2MarkupMojo : Unsupported major.minor version 52.0
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>io.github.swagger2markup:swagger2markup-maven-plugin:1.3.1
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/hpatel/.m2/repository/io/github/swagger2markup/swagger2markup-maven-plugin/1.3.1/swagger2markup-maven-plugin-1.3.1.jar
[ERROR] urls[1] = file:/home/hpatel/.m2/repository/io/github/swagger2markup/swagger2markup-import-files-ext/1.3.1/swagger2markup-import-files-ext-1.3.1.jar
[ERROR] urls[2] = file:/home/hpatel/.m2/repository/io/github/swagger2markup/swagger2markup-extension-commons/1.3.1/swagger2markup-extension-commons-1.3.1.jar
[ERROR] urls[3] = file:/home/hpatel/.m2/repository/io/github/swagger2markup/swagger2markup/1.3.1/swagger2markup-1.3.1.jar
[ERROR] urls[4] = file:/home/hpatel/.m2/repository/io/github/swagger2markup/markup-document-builder/1.1.1/markup-document-builder-1.1.1.jar
[ERROR] urls[5] = file:/home/hpatel/.m2/repository/org/slf4j/slf4j-api/1.7.18/slf4j-api-1.7.18.jar
[ERROR] urls[6] = file:/home/hpatel/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar
[ERROR] urls[7] = file:/home/hpatel/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar
[ERROR] urls[8] = file:/home/hpatel/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
[ERROR] urls[9] = file:/home/hpatel/.m2/repository/nl/jworks/markdown_to_asciidoc/markdown_to_asciidoc/1.0/markdown_to_asciidoc-1.0.jar
[ERROR] urls[10] = file:/home/hpatel/.m2/repository/org/pegdown/pegdown/1.4.2/pegdown-1.4.2.jar
[ERROR] urls[11] = file:/home/hpatel/.m2/repository/org/parboiled/parboiled-java/1.1.6/parboiled-java-1.1.6.jar
[ERROR] urls[12] = file:/home/hpatel/.m2/repository/org/parboiled/parboiled-core/1.1.6/parboiled-core-1.1.6.jar
[ERROR] urls[13] = file:/home/hpatel/.m2/repository/org/ow2/asm/asm/4.1/asm-4.1.jar
[ERROR] urls[14] = file:/home/hpatel/.m2/repository/org/ow2/asm/asm-tree/4.1/asm-tree-4.1.jar
[ERROR] urls[15] = file:/home/hpatel/.m2/repository/org/ow2/asm/asm-analysis/4.1/asm-analysis-4.1.jar
[ERROR] urls[16] = file:/home/hpatel/.m2/repository/org/ow2/asm/asm-util/4.1/asm-util-4.1.jar
[ERROR] urls[17] = file:/home/hpatel/.m2/repository/org/jsoup/jsoup/1.8.1/jsoup-1.8.1.jar
[ERROR] urls[18] = file:/home/hpatel/.m2/repository/io/swagger/swagger-compat-spec-parser/1.0.25/swagger-compat-spec-parser-1.0.25.jar
[ERROR] urls[19] = file:/home/hpatel/.m2/repository/io/swagger/swagger-core/1.5.12/swagger-core-1.5.12.jar
[ERROR] urls[20] = file:/home/hpatel/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.8.4/jackson-annotations-2.8.4.jar
[ERROR] urls[21] = file:/home/hpatel/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.8.4/jackson-databind-2.8.4.jar
[ERROR] urls[22] = file:/home/hpatel/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.8.4/jackson-core-2.8.4.jar
[ERROR] urls[23] = file:/home/hpatel/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.8.4/jackson-dataformat-yaml-2.8.4.jar
[ERROR] urls[24] = file:/home/hpatel/.m2/repository/org/yaml/snakeyaml/1.15/snakeyaml-1.15.jar
[ERROR] urls[25] = file:/home/hpatel/.m2/repository/io/swagger/swagger-models/1.5.12/swagger-models-1.5.12.jar
[ERROR] urls[26] = file:/home/hpatel/.m2/repository/io/swagger/swagger-annotations/1.5.12/swagger-annotations-1.5.12.jar
[ERROR] urls[27] = file:/home/hpatel/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar
[ERROR] urls[28] = file:/home/hpatel/.m2/repository/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar
[ERROR] urls[29] = file:/home/hpatel/.m2/repository/io/swagger/swagger-parser/1.0.25/swagger-parser-1.0.25.jar
[ERROR] urls[30] = file:/home/hpatel/.m2/repository/org/slf4j/slf4j-ext/1.6.3/slf4j-ext-1.6.3.jar
[ERROR] urls[31] = file:/home/hpatel/.m2/repository/ch/qos/cal10n/cal10n-api/0.7.4/cal10n-api-0.7.4.jar
[ERROR] urls[32] = file:/home/hpatel/.m2/repository/com/github/fge/json-schema-validator/2.2.3/json-schema-validator-2.2.3.jar
[ERROR] urls[33] = file:/home/hpatel/.m2/repository/joda-time/joda-time/2.3/joda-time-2.3.jar
[ERROR] urls[34] = file:/home/hpatel/.m2/repository/com/github/fge/json-schema-core/1.2.1/json-schema-core-1.2.1.jar
[ERROR] urls[35] = file:/home/hpatel/.m2/repository/com/github/fge/uri-template/0.9/uri-template-0.9.jar
[ERROR] urls[36] = file:/home/hpatel/.m2/repository/org/mozilla/rhino/1.7R4/rhino-1.7R4.jar
[ERROR] urls[37] = file:/home/hpatel/.m2/repository/com/googlecode/libphonenumber/libphonenumber/6.0/libphonenumber-6.0.jar
[ERROR] urls[38] = file:/home/hpatel/.m2/repository/javax/mail/mailapi/1.4.3/mailapi-1.4.3.jar
[ERROR] urls[39] = file:/home/hpatel/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar
[ERROR] urls[40] = file:/home/hpatel/.m2/repository/com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.jar
[ERROR] urls[41] = file:/home/hpatel/.m2/repository/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
[ERROR] urls[42] = file:/home/hpatel/.m2/repository/com/github/fge/json-patch/1.6/json-patch-1.6.jar
[ERROR] urls[43] = file:/home/hpatel/.m2/repository/com/github/fge/jackson-coreutils/1.6/jackson-coreutils-1.6.jar
[ERROR] urls[44] = file:/home/hpatel/.m2/repository/com/github/fge/msg-simple/1.1/msg-simple-1.1.jar
[ERROR] urls[45] = file:/home/hpatel/.m2/repository/com/github/fge/btf/1.2/btf-1.2.jar
[ERROR] urls[46] = file:/home/hpatel/.m2/repository/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
[ERROR] urls[47] = file:/home/hpatel/.m2/repository/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
[ERROR] urls[48] = file:/home/hpatel/.m2/repository/org/apache/commons/commons-configuration2/2.1/commons-configuration2-2.1.jar
[ERROR] urls[49] = file:/home/hpatel/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
[ERROR] urls[50] = file:/home/hpatel/.m2/repository/commons-beanutils/commons-beanutils/1.9.2/commons-beanutils-1.9.2.jar
[ERROR] urls[51] = file:/home/hpatel/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar
[ERROR] urls[52] = file:/home/hpatel/.m2/repository/org/apache/commons/commons-collections4/4.1/commons-collections4-4.1.jar
[ERROR] urls[53] = file:/home/hpatel/.m2/repository/io/javaslang/javaslang/2.0.5/javaslang-2.0.5.jar
[ERROR] urls[54] = file:/home/hpatel/.m2/repository/io/javaslang/javaslang-match/2.0.5/javaslang-match-2.0.5.jar
[ERROR] urls[55] = file:/home/hpatel/.m2/repository/ch/netzwerg/paleo-core/0.10.2/paleo-core-0.10.2.jar
[ERROR] urls[56] = file:/home/hpatel/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar
[ERROR] urls[57] = file:/home/hpatel/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.plexus/0.3.0/org.eclipse.sisu.plexus-0.3.0.jar
[ERROR] urls[58] = file:/home/hpatel/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[59] = file:/home/hpatel/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
[ERROR] urls[60] = file:/home/hpatel/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar
[ERROR] urls[61] = file:/home/hpatel/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.0/org.eclipse.sisu.inject-0.3.0.jar
[ERROR] urls[62] = file:/home/hpatel/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[63] = file:/home/hpatel/.m2/repository/org/apache/maven/plugin-tools/maven-plugin-annotations/3.4/maven-plugin-annotations-3.4.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

Any help will be appreciated. Thanks

**Comment by RobWin** [comment]
Error is: `Unsupported major.minor version 52.0`.
Do you use JDK8? JDK8 is required.

**Comment by hpatel2017** [comment]
Sorry my bad... updated JAVA_HOME to use jdk8 by maven. Thanks.
