### ISSUE TITLE
Markup not generated.

### ISSUE THREAD

**Issue by hpatel2017** [Swagger2Markup/swagger2markup-maven-project-template#7]
I changed swagger.input in pom.xml to remote URL which has api-docs.json based on swagger version 1.2 and list of resources which are java resources annotated by swagger-core. swagger-ui is loading fine.
When i tried to using swagger2markup, it was build success and generated html/pdf but both are empty with dummy texts. Looks like it only picked up title from remote api-docs.json to show at top of html/pdf.

Am I missing some configuration ? Swagger-ui is very slow so want to generate static offline version.

**Comment by RobWin** [comment]
Swagger2Markup is using swagger-parser to parser 1.2 and 2.0 specs.
I guess its an issue of swagger-parser and not Swagger2markup.

**Comment by hpatel2017** [comment]
Yes, fixed it. Made base path blank from resource list and added full path in each resource. 
I also got Tags related error, so commented out pathsGroupBy, but now getting different error. 

[ERROR] Failed to execute goal io.github.swagger2markup:swagger2markup-maven-plugin:1.3.1:convertSwagger2markup (default-cli) on project swagger2markup-maven-project-template: Failed to execute goal 'convertSwagger2markup': Type of parameter 'null' must not be blank -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.github.swagger2markup:swagger2markup-maven-plugin:1.3.1:convertSwagger2markup (default-cli) on project swagger2markup-maven-project-template: Failed to execute goal 'convertSwagger2markup'
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoFailureException: Failed to execute goal 'convertSwagger2markup'
        at io.github.swagger2markup.Swagger2MarkupMojo.execute(Swagger2MarkupMojo.java:74)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
Caused by: java.lang.NullPointerException: Type of parameter 'null' must not be blank
        at org.apache.commons.lang3.Validate.notBlank(Validate.java:448)
        at io.github.swagger2markup.internal.type.BasicType.<init>(BasicType.java:41)
        at io.github.swagger2markup.internal.type.BasicType.<init>(BasicType.java:36)
        at io.github.swagger2markup.internal.utils.ModelUtils.getType(ModelUtils.java:75)
        at io.github.swagger2markup.internal.component.DefinitionComponent.typeSection(DefinitionComponent.java:131)
        at io.github.swagger2markup.internal.component.DefinitionComponent.apply(DefinitionComponent.java:80)
        at io.github.swagger2markup.internal.document.DefinitionsDocument.applyDefinitionComponent(DefinitionsDocument.java:160)
        at io.github.swagger2markup.internal.document.DefinitionsDocument.buildDefinition(DefinitionsDocument.java:138)
        at io.github.swagger2markup.internal.document.DefinitionsDocument.lambda$buildDefinitionsSection$0(DefinitionsDocument.java:102)
        at java.util.TreeMap.forEach(TreeMap.java:1005)
        at io.github.swagger2markup.internal.document.DefinitionsDocument.buildDefinitionsSection(DefinitionsDocument.java:99)
        at io.github.swagger2markup.internal.document.DefinitionsDocument.apply(DefinitionsDocument.java:86)
        at io.github.swagger2markup.Swagger2MarkupConverter.applyDefinitionsDocument(Swagger2MarkupConverter.java:203)
        at io.github.swagger2markup.Swagger2MarkupConverter.toFolder(Swagger2MarkupConverter.java:184)
        at io.github.swagger2markup.Swagger2MarkupMojo.execute(Swagger2MarkupMojo.java:69)


Is it because i commented out pathsGroupedBy property ?

**Comment by RobWin** [comment]
No it seems a property/model is missing a type like string, int, ...?

**Comment by hpatel2017** [comment]
Is it a way to get more debug info on which property/model ? Thanks for all help.

**Comment by RobWin** [comment]
Yes, Swagger2Markup is using Slf4j. You can configure maven and  run it in DEBUG level https://maven.apache.org/maven-logging.html
